export type GeneraterFormatType =
  | "azteccode"
  | "rationalizedCodabar"
  | "code39"
  | "code93"
  | "code128"
  | "datamatrix"
  | "ean8"
  | "ean13"
  | "interleaved2of5"
  | "maxicode"
  | "pdf417"
  | "qrcode"
  | "databaromni"
  | "databarexpanded"
  | "upca"
  | "upce"
  | "ean2";

export type ReaderFormatType =
  | "AZTEC"
  | "CODABAR"
  | "CODE_39"
  | "CODE_93"
  | "CODE_128"
  | "DATA_MATRIX"
  | "EAN_8"
  | "EAN_13"
  | "ITF"
  | "MAXICODE"
  | "PDF_417"
  | "QR_CODE"
  | "RSS_14"
  | "RSS_EXPANDED"
  | "UPC_A"
  | "UPC_E"
  | "UPC_EAN_EXTENSION";
